---
- name: labScript
  hosts: localhost
  gather_facts: false
  collections:
    - davidban77.gns3
  tasks:
    - name: loadLocalSettings
      ansible.builtin.include_vars:
        file: "vars/local.yml"
      no_log: false
      tags: test
    # because we can't set and use a variable in the same set_fact we need to have a separate task
    #   to default these values - these are commands we can set from --extra-vars or "e" on the command line
    # The freaking builtinType below does NOT freaking exist. It will only exist if you call -e builtinType=whatever as
    # you call the pb. so example ansible-playbook thisfile.yml -e builtinType=builtInName. 
    # Also, builtinType is not assined the default value ('builtin' in this case). The value of builtinType, 
    # if called in the playbook, is assigned to variabme mgmtImageType
    - name: setImageType
      set_fact:
        imageType: "{{ extra_var_switchImage | default('veos') }}"
        mgmtImageType: "{{ extra_var_mgmtImage | default('builtin') }}"
        execute: "{{ execute | default('create') }}"
      # no_log: True
      #comment out execute above, then delete this comment  
      tags: test

    # set the lab setup yml file name - Rockies.yml, Rockieslab.yml etc. The task that calls the lab will add .yml to name
    # so exclude .yml
    - name: setLab
      set_fact:
        lab: "veosRockieslab"
      tags: test

    # pull out a single std_image from the images dict loaded from local.yml. The "imageType" is from set_fact above.
    - name: chooseStdImage
      set_fact:
        std_image: "{{ std_images[imageType] }}"
      no_log: false
      tags: test

 # pull out a single mgmt_image from the images dict loaded from local.yml. The "mgmtImageType" is from set_fact above.
    - name: chooseMgmtImage
      set_fact:
        mgmt_image: "{{ mgmt_images[mgmtImageType] }}"
      no_log: false
      tags: test 

    - name: Testing for Image and Lab variables 
      debug:  
        msg: 
          - "{{ std_image.name }}" 
          - "{{ mgmt_image }}"
          - "{{ mgmtImageType }}"
          - "{{ lab }}"
      tags: test


    # load the lab and fill in any variable substituions
    - name: loadLab
      ansible.builtin.include_vars:
        file: "labs/{{ lab }}.yml"
      # no_log: true

    - name: Operationionalize and Execute!!!
      debug:
        msg: "Running {{ execute }} for Lab: {{ gns3_project_name }}"

    # call the right role to either create or delete the lab
    - name: create
      when: execute == "create"
      import_role:
        name: create_lab

    - name: delete
      when: execute == "delete"
      block:
        - import_role:
            name: delete_lab


      