---
- name: labScript
  hosts: localhost
  gather_facts: false

  tasks:
    - name: loadLocalSettings
      ansible.builtin.include_vars:
        file: "vars/local.yml"
      no_log: false

# The freaking builtinType below does NOT freaking exist. It will only exist if you call -e builtinType=whatever as
# you call the pb. so example ansible-playbook thisfile.yml -e builtinType=builtInName. Also, builtinType is not assined the
# default value ('builtin' in this case). The value of builtinType, if called in the playbook, is assigned to variabme mgmtImageType
    - name: setImageType
      set_fact:
        imageType: "{{ imageType | default('veos') }}"
        mgmtImageType: "{{ builtinType | default('builtin') }}"
        execute: "{{ execute | default('create') }}" 

    # pull out a single std_image from the images dict loaded from local.yml. The "imageType" is from set_fact above.
    - name: chooseStdImage
      set_fact:
        std_image: "{{ std_images[imageType] }}"

 # pull out a single mgmt_image from the images dict loaded from local.yml. The "mgmtImageType" is from set_fact above.
    - name: chooseMgmtImage
      set_fact:
        mgmt_image: "{{ mgmt_images[mgmtImageType] }}"

    - name: Testing for Image and Lab variables 
      debug:  
        msg: 
          - " line1: {{ std_image.name }}" 
          - " line2: {{ mgmt_image }}"
          - " line3:  {{ mgmtImageType }}"
          - " line4:  {{ builtinType }}"




      