---
# this is the url, fqdn or ip of your gns3 srver
gns3_url: "http://192.168.10.22"
# the port to use to connect to the server.  80 is probably the sensible choice, but 3080 may be needed for older installs
gns3_port: 80
# start/stop strategy for nodes.  valid options are "all" or "one_by_one"
gns3_nodes_strategy: all
# default symbol alterante :/symbols/affinity/square/blue/switch_multilayer.svg
default_symbol: ":/symbols/affinity/circle/blue/atm.svg"
# this string is prepended to all created labs locally.  default is the empty string, '' if not defined
# the default project name will be
#   [PREFIX]RockiesLab-[image.type]
PREFIX: "nutz"

# modify the name variables below to reflect the installed/desired gns3 templates to use for each image type.
#   do not change other variables
std_images:
  ceos:
    name: "ceos-lab 4.28.0F"
    interfacePrefix: "eth"
    type: "ceos"
    managementPort: "eth0"
  veos:
    name: "EOS-4.28.1"
    interfacePrefix: "Eth"
    type: "veos"
    managementPort: "ma1"
mgmt_images:
  veos:
    name: "EOS-4.28.1-mgmt"
    interfacePrefix: "Eth"
    type: "veos"
    managementPort: "ma1"